[package]
name = "client-common"
version = "0.1.0"
authors = ["paulg"]
edition = "2018"

[dependencies]
common = { path = "../common" }
tracing = "0.1"
reqwest = "0.11"
rand = "0.8"
rand_core = "0.6"
getrandom = { version = "0.2", features = ["js"] }
anyhow = "1.0"

rmp-serde = "0.15"

# password and email check
zxcvbn = {git = "https://github.com/1Password/zxcvbn-rs.git", branch = "master"} # includes a patch to work in wasm
pwned = "0.4"
validator = { version = "0.12", default-features = false }

opaque-ke = { git = "https://github.com/PaulGrandperrin/opaque-ke.git", branch = "master" }

xchacha8blake3siv = { git = "https://github.com/PaulGrandperrin/XChacha8Blake3Siv.git" }
ed25519-dalek = { git = "https://github.com/PaulGrandperrin/ed25519-dalek.git" }
aead = "0.3"