[package]
name = "server"
version = "0.1.0"
authors = ["Paul Grandperrin <paul.grandperrin@gmail.com>"]
edition = "2018"

default-run = "server"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common/"}
tracing = "0.1"
tracing-subscriber = "0.2"
async-std = { version = "1.8", features = ["attributes"]}
tide = "0.15"
tide-tracing = "0.0"
rmp-serde = "0.15"
rand = "0.8"
rand_core = "0.6"
anyhow = "1.0"
sqlx = { version = "0.4", default-features = false, features = [ "mysql","runtime-async-std-rustls" ] }
chrono = "0.4"
structopt = "0.3"
generic-bytes = "0.1"
generic-array = "0.14"
serde = "1.0"
async-trait = "0.1"

opaque-ke = { git = "https://github.com/PaulGrandperrin/opaque-ke.git", branch = "master" }