[package]
name = "server"
version = "0.1.0"
authors = ["Paul Grandperrin <paul.grandperrin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common/"}
tracing = "0.1"
tracing-subscriber = "0.2"
async-std = { version = "1.8", features = ["attributes"]}
tide = "0.15"
rmp-serde = "0.15"
rand = "0.7"
anyhow = "1.0"

opaque-ke = { git = "https://github.com/kevinlewi/opaque-ke.git", branch = "docs_cleanup" }