[package]
name = "server"
version = "0.1.0"
authors = ["Paul Grandperrin <paul.grandperrin@gmail.com>"]
edition = "2018"

default-run = "server"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common/", features = ["server"]}
tracing = "0.1"
tracing-subscriber = "0.2"
#tracing-futures = "0.2"
async-std = { version = "1", features = ["attributes", "tokio1"]}
#tokio = { version = "1", features = ["full"] }
warp = "0.3"
tide = "0.16"
tide-tracing = "0.0"
rmp-serde = "0.15"
rand = "0.8"
rand_core = "0.6"
eyre = "0.6"
color-eyre = "0.5"
sqlx = { version = "0.5", default-features = false, features = [ "mysql","runtime-async-std-rustls" ] }
#chrono = "0.4"
structopt = "0.3"
generic-bytes = "0.1"
generic-array = "0.14"
serde = "1.0"
#async-trait = "0.1"
sha2 = "0.9"
futures = "0.3"
toml = "0.5"
bs58 = "0.4"

opaque-ke = { git = "https://github.com/novifinancial/opaque-ke.git"}
