[package]
name = "server"
version = "0.1.0"
authors = ["Paul Grandperrin <paul.grandperrin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common/"}
tracing = "0.1"
tracing-subscriber = "0.2"
async-std = { version = "1.8", features = ["attributes"]}
tide = "0.15"
tide-tracing = "0.0"
rmp-serde = "0.15"
rand = "0.7"
rand_core = "*" # 0.6
anyhow = "1.0"
sqlx = { version = "0.4", default-features = false, features = [ "mysql","runtime-async-std-rustls" ] }

opaque-ke = { git = "https://github.com/novifinancial/opaque-ke.git", branch = "master" }