[package]
name = "common"
version = "0.1.0"
authors = ["Paul Grandperrin <paul.grandperrin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.2"
serde = {version = "1.0", features = ["derive"]}

opaque-ke = "0.2"
curve25519-dalek = "3.0"
sha2 = "0.9"